<?php
return [
  'class' => 'pagination  pagination-sm justify-content-center',
  'itemclass' => 'page-item',
  'linkclass' => 'page-link',
  'activelink' => ' active',
  'disabledlink' => ' disabled',
  'withoutdots' => false,
  'pageparam' => 'page',
  'initialparam' => 'initial',
  'valueforall'=> 'all',
  'type' => 'numeric',
  'nbpages' => 1,
  'max_pages_without_dots' => 9,
  'items_before_after_current' => 2,
  'params' => [],
  'getparams' => [],
  'srcurrent' => ' <span class="sr-only">(current)</span>',
  'previousbuttoncontent' => '<span aria-hidden=\"true\">&laquo;</span>',
  'nextbuttoncontent' => '<span aria-hidden=\"true\">&raquo;</span>',
];
